Add parameter for timeout of plan solver
PlanSys2/ros2_planning_system pull request #307
Opened 2024-03-18 15:53 UTC by roveri-marco

Added the possibility to set at run time the timeout for waiting for a solution from the underneath called planner.
This will fix issue #243

2024-03-22 05:31 UTC, fmrico commented
Thanks @roveri-marco . Pending of fixing CI

2024-03-31 16:31 UTC, fmrico commented
CI seems to be fixed, but it is applying old pipeline. Can you rebase/merge?

2024-04-04 10:37 UTC, fmrico requested changes

2024-04-04 10:37 UTC, fmrico commented on plansys2_core/include/plansys2_core/PlanSolverBase.hpp
> +    const int solver_timeout = 15) = 0;
Why `int` for the timeout? I would prefer a rclcpp::Duration? In the parameter is ok. You can document that this needs to be seconds, but internally I prefer this type.

```
using namespace std::chrono_literals;
...
const rclcpp::Duration  solver_timeout = 15s) = 0;
```

2024-04-04 10:37 UTC, fmrico commented on plansys2_bringup/params/plansys2_params.yaml
> +    plan_solver_timeout: 15
Here it is okay, but I prefer double instead of int.

2024-04-04 10:37 UTC, fmrico commented on plansys2_planner/src/plansys2_planner/PlannerClient.cpp
> +  node_->declare_parameter("plan_solver_timeout", solver_timeout_);
Here we should need to convert from double/float to rclcpp::Duration

2024-04-04 10:38 UTC, fmrico commented
Everything LGTM in this PR, except the type concerns in the review

Thanks @roveri-marco

2024-04-05 07:54 UTC, roveri-marco commented
> Everything LGTM in this PR, except the type concerns in the review
> 
> Thanks @roveri-marco

I'll fix in the forthcoming days.

2024-04-07 08:11 UTC, fmrico approved these changes

2024-04-07 08:11 UTC, merged

2024-04-07 08:11 UTC, fmrico commented
Merging!! :rocket: